### PR TITLE
update pulp github url

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Comment by chexxor** [comment]
Thanks for the fix! We'll have to fix this link in [ecosystem/Editor-and-tool-support.md](https://github.com/purescript/documentation/blob/e2de1022d79ed980384ca31f90ca67484d775b07/ecosystem/Editor-and-tool-support.md) too, unless you add a patch with this PR.

Can you add a patch to include yourself in the Contributors list? https://github.com/purescript/documentation/blob/master/CONTRIBUTORS.md
I think we need that before we can merge.

**Comment by juhp** [comment]
I can but it is such a small contribution, but if you really need it...

**Comment by chexxor** [comment]
Yeah, I'm not an expert on copyright law, but we need explicit license to use the patches from all contributors if we want to redistribute or such.

It's motivated by the effort started in this issue: https://github.com/purescript/documentation/issues/151

**Comment by hdgarrood** [comment]
It’s likely to be a lot easier in the long run to have a rule which everyone can agree on and which has no ambiguity, I think.

**Comment by hdgarrood** [comment]
Everyone can agree on an interpretation of, that is.

**Comment by juhp** [comment]
Sure of course I am happy to oblige - done!

(I would have been just as happy if someone had merged by hand :)

**Comment by chexxor** [comment]
@juhp Thanks so much for helping improve the docs!

**Pull request merged**
