### PR TITLE
Add a hint for using purescript built-in globbing

### PR DESCRIPTION
**Pull request by Profpatsch**
Instead of shell globbing, as was explained in https://github.com/purescript/documentation/pull/190#issuecomment-404331012

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Could you please also add yourself the CONTRIBUTORS.md list?

**Comment by kRITZCREEK** [comment]
ping @Profpatsch, I'd like to get this merged, if you could just add yourself to the `CONTRIBUTORS.md` in the project root. Thanks!

**Comment by Profpatsch** [comment]
Done.

**Comment by kRITZCREEK** [comment]
Thanks!

**Pull request merged**
