### PR TITLE
Remove some old entries, and the wish list section

### PR DESCRIPTION
**Pull request by paf31**
The wish list section should really be turned into issues on the appropriate repos.

### CODE REVIEW

**Comment by hdgarrood** [comment]
:+1: I'm pretty sure we have all of those now, apart from qualify imports, find references (for refactoring / renaming), and fix TransitiveExportError automatically anyway.

**Comment by kRITZCREEK** [comment]
Not sure if we want to track them on the compiler issue tracker... I've created a `psc-ide` project to gather the features I'd like to implement here https://github.com/purescript/purescript/projects/2. 

I think I've already got the "find references" wish covered with the "find usages" issue.

**Comment by hdgarrood** [comment]
Ok cool - I'll leave it up to you to decide if/how to track the other 2.

**Pull request merged**
