### PR TITLE
Added a section about import hiding

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by clayrat** [comment]
Maybe we should also mention that name in the beginning of `Importing Modules` section then?

**Comment by hdgarrood** [comment]
Yes, I think that would be good.

**Comment by clayrat** [comment]
Any suggestion to reword then? `This` was already there before I edited tho.

**Comment by hdgarrood** [comment]
Oh oops, so it was. In that case I'll merge this and address that later. Thank you!

**Pull request merged**
