### PR TITLE
Add example for `case _ of`

### PR DESCRIPTION
**Pull request by craigdallimore**
I noticed there was not an example for for `case _ of` in the documentation, is this an appropriate way to describe it?

### CODE REVIEW

**Comment by hdgarrood** [comment]
We should definitely add an example of this, but I think it would be a bit clearer to say something like "A binding can be avoided by using a single underscore in place of the expression to match on; in this context, the underscore represents an *anonymous argument*."

I think we should also write out the equivalent code, i.e. we should mention that `case _ of {...}` is the same as `\x -> case x of {...}` - just to make it as clear as possible.

**Comment by craigdallimore** [comment]
Thank you, how does this look?

**Comment by chexxor** [comment]
LGTM! Thanks for adding notes of case-syntax's anonymous argument capability!

**Comment by hdgarrood** [comment]
Thank you!

**Pull request merged**
