### PR TITLE
Updates to type classes & minor edits

### PR DESCRIPTION
**Pull request by LiamGoodacre**
There's still more to do but I think this is better than what we had.  Any thoughts?

### CODE REVIEW

**Comment by hdgarrood** [comment]
Sorry, but I don't think this is the style of documentation we want here, really. The stuff inside the language/ directory is really meant to be a reference, i.e. aimed at people who have some idea of how this part of the language works already &mdash; there's already PureScript by Example and plenty of Haskell resources for at people who haven't come across typeclasses before. I think the documentation here should be more direct and concise.

Also I don't think we want to link to 2014's 24 days of PureScript, it's probably too far out of date now.

**Comment by LiamGoodacre** [comment]
Thanks for your feedback, that makes sense.
I've trimmed my changes down to just minor edits :)

**Comment by hdgarrood** [comment]
That looks good :) One tiny nit - can you please use the full version of the bower command i.e. `bower install --save` rather than `bower i -S`?

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
