### PR TITLE
Revert "FFI.md typo (#388)"

### PR DESCRIPTION
**Pull request by jamesdbrock**
This reverts commit 878390c5d4c40adef2074774625fb59465788c5d.

This reverts #388

### CODE REVIEW

**Comment by jamesdbrock** [comment]
Here's the reversion PR, if you decide that you want to revert.

**Review by hdgarrood — APPROVED** [review]

**Comment by JordanMartinez** [comment]
@hdgarrood Why don't we use "has kind `Type`" rather than "at kind `Type`"?
```diff
- To give meaningful types to those functions, it might be useful to define a type `Frob` at kind `Type`.
+ To give meaningful types to those functions, it might be useful to define a type `Frob` that has kind `Type`.

**Comment by hdgarrood** [comment]
That works too

**Comment by JordanMartinez** [comment]
@jamesdbrock Which rendering makes more sense to you. The original one to which this PR reverts or the rendering I provided above?

**Comment by jamesdbrock** [comment]
> @jamesdbrock Which rendering makes more sense to you. The original one to which this PR reverts or the rendering I provided above?

I like yours.

**Comment by JordanMartinez** [comment]
Then let's go with the "has kind `Type`" rendering.

**Pull request merged**
