### PR TITLE
Update Differences-from-Haskell.md

### PR DESCRIPTION
**Pull request by kcsongor**
`DataKinds` (sort of) and `KindSignatures` are supported by PS

### CODE REVIEW

**Comment by hdgarrood** [comment]
I think the way user-defined kinds works in PureScript is different enough from Haskell's `DataKinds` that it's probably best not to list it here..?

**Comment by kcsongor** [comment]
This is a good point, and I thought of this too. As far as I know, the difference is that in PureScript, type constructors of user-defined kinds can't be used as values, but I don't think that's a very important aspect of the extension (though this is just my opinion).

On the other hand, the ability to define kinds (and use literals in types) would be important to communicate somehow.

For me personally, this list was the single most important part of the document, and I know that if I didn't see `DataKinds` on the list, I wouldn't have expected to find this info elsewhere, though again, this is just me. What do you think?

**Comment by hdgarrood** [comment]
What about putting DataKinds on the list, with a short explanation below, plus a link to https://github.com/purescript/documentation/blob/master/language/Types.md#kind-system?

**Comment by kcsongor** [comment]
Yes, that's good, I've updated the PR. Do you think this explanation makes sense? I put it inline, but maybe it would be better below the list...

**Comment by hdgarrood** [comment]
Yes, that looks good, although I think I'd prefer it below the list.

**Comment by hdgarrood** [comment]
What does "open" mean here?

**Comment by kcsongor** [comment]
I meant that you can define a kind, and then add new constructors to it anytime
```hs
foreign import Kind K
foreign import data A :: K
foreign import data B :: K
```

whereas in Haskell, you can't extend an existing kind after it's defined.

**Comment by hdgarrood** [comment]
Ahh, yes, of course, thanks.

**Comment by hdgarrood** [comment]
Thank you!

**Pull request merged**
