### PR TITLE
Recommend using `unsafePartialBecause`

### PR DESCRIPTION
**Pull request by chexxor**
Fixes https://github.com/purescript/documentation/issues/23

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks great! It might be worth adding that `unsafePartial` should probably be preferred if you're worried about performance, since `unsafePartial` will be inlined as of the next compiler release.

**Comment by chexxor** [comment]
Great idea @hdgarrood! I've updated the branch to include a commit which includes that inlining bit.

**Comment by hdgarrood** [comment]
I'm sorry to mess you around, but actually I've been thinking about `unsafePartialBecause` and it's actually not so clear to me that we should be recommending it. I'm going to open an issue on purescript-partial when I get a moment.

**Comment by chexxor** [comment]
Sure, no problem.

**Comment by hdgarrood** [comment]
https://github.com/purescript/purescript-partial/issues/7

**Comment by hdgarrood** [comment]
Seems like we shouldn't be recommending `unsafePartialBecause` after all (see discussion on purescript/purescript-partial#7), so I'm going to close this. Thanks though!

**Pull request closed without merging**
