### PR TITLE
Add "Indentation in binding blocks"

### PR DESCRIPTION
**Pull request by chexxor**

### CODE REVIEW

**Comment by chexxor** [comment]
Interestingly, if `let` is 4 spaces, its following `in` can be 2 spaces.
Same for `in` block - if `in` is 2 spaces, its body can be indented 1 space.
Same for `do` block - if `do` is 6 spaces, its body can be indented 1 space.
These are all absolute indentation, where absolute means from the beginning of the line, not the parent's indentation level.

**Comment by splodingsocks** [comment]
Awesome, thanks for adding that, @chexxor !

**Comment by hdgarrood** [comment]
This is useful information to have but it should be in the Syntax.md file instead of this one.

**Comment by hdgarrood** [comment]
Hmm, it seems like much of what's currently in the 'Values' file is in the wrong place, actually. I'll merge this for now and we can address that later.

**Pull request merged**
