### PR TITLE
Various imports error/warnings entries

### PR DESCRIPTION
**Pull request by nwolverson**

### CODE REVIEW

**Comment by hdgarrood** [comment]
This might be a good opportunity to make a start on #158. Also would you mind changing "This error is auto-fixable" to "This warning is auto-fixable"? Finally do you think there's something we can link to which explains what that means?

**Comment by nwolverson** [comment]
Yeah I was considering taking a pass at a bunch of the imports issues. I want to indicate the class of warnings that the compiler provides suggestions to fix which can be applied with purescript-suggest, pscid or editor plugins - I wonder if there's a better wording which can be used consistently. 

Should I maybe create a page in `guides/` which can be linked to that explains these options?

**Comment by hdgarrood** [comment]
I think the wording is fine, I'm just a little concerned about how useful it will be for people who don't have the context.

> Should I maybe create a page in guides/ which can be linked to that explains these options?

That would be great :+1:

**Comment by nwolverson** [comment]
I've added a short error suggestions guide, and linked this, also went through a batch of warnings around imports.

**Comment by chexxor** [comment]
LGTM :+1:

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
