### PR TITLE
Haskell Differences: Operator Sections

### PR DESCRIPTION
**Pull request by stephencelis**
A small gotcha for me as I've started experimenting.

I do wish deprecated features had compiler errors :) Took me a bit of sleuthing to track this down!

### CODE REVIEW

**Comment by hdgarrood** [comment]
Definitely worth mentioning this here :+1: although I think we generally say that PureScript does have operator sections, albeit with syntax slightly different to Haskell's, so I think it would be good to make some minor wording changes to reflect this.

**Comment by stephencelis** [comment]
Happy to reword anything!

**Comment by hdgarrood** [comment]
That reminds me, we should fully document all the `_` forms, like `case _ of [...]` and `if _ then x else y`; have we done that already?

**Comment by hdgarrood** [comment]
(Not that that needs to happen now / in this PR)

**Comment by chexxor** [comment]
@hdgarrood Created an issue for that: https://github.com/purescript/documentation/issues/52

**Comment by hdgarrood** [comment]
So I think it would be better to say that PureScript does have operator sections, but the syntax is slightly different to Haskell's. That's more in line with what we've written elsewhere, at least. Other than that I think this looks good :+1:

**Comment by stephencelis** [comment]
@hdgarrood Updated with something that hopefully works 😄

**Comment by hdgarrood** [comment]
I'd prefer to avoid the phrase "partial application notation" because I think it suggests that it's a more general thing that works in a wide variety of cases; really this is just one example out of a very select few syntactic forms where we allow underscores for anonymous function arguments like this, and many of those forms don't even involve any partial application. I think just "operator sections" is a better description of them.

**Comment by stephencelis** [comment]
@hdgarrood Ah, I took that description from elsewhere—an old commit message or something. I can remove!

**Comment by stephencelis** [comment]
Updated. I do think it's a bit confusing to ignore `_`'s slightly wider use, though I imagine https://github.com/purescript/documentation/issues/52 will take care of that.

**Comment by hdgarrood** [comment]
Thank you! Yes, it would probably be good to link to these expanded docs from here once they exist.

**Comment by chexxor** [comment]
@stephencelis Thanks for the addition!

**Pull request merged**
