### PR TITLE
Reduce dependency manager scope to Bower and address common problems

### LINKED ISSUE #227: Clarify Bower vs psc-package pros/cons for new learners
Continuing from #199's [comment and down](https://github.com/purescript/documentation/pull/199#issuecomment-442146447), explain the differences of Bower and psc-package in a format that is friendly to new learners.

My learning repo's [Dependency Mangers.md](https://github.com/JordanMartinez/purescript-jordans-reference/blob/development/01-Build-Tools/01-Tool-Comparisons/01-Dependency-Managers.md) file already explains this but...

> That page looks good but on reflection I'm not sure it's appropriate to expose all that to someone who is just trying to get something working during their first experience with the language. I'm going to close this PR for now, but feel free to open issues if you want to revive this discussion. [Original comment](https://github.com/purescript/documentation/pull/199#issuecomment-453795212)

This is a valid cricitism. Ever since my discussion with [thomashoneyman in his RW Halogen App](https://github.com/thomashoneyman/purescript-halogen-realworld/issues/13#issuecomment-451354091), I've updated the repo's [Install Guide.md](https://github.com/JordanMartinez/purescript-jordans-reference/blob/development/00-Getting-Started/01-Install-Guide.md) to present `spacchetti` and `dhall-to-json` as optional dependencies that people can later install if they desire. I haven't yet documented/covered Spago, so keep that in mind, too.

Still, the question remains: what needs to be stripped/added from these two files to make things easier for a new learner?

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #227 using the 3 actions I listed in my last comment

### CODE REVIEW

**Comment by hdgarrood** [comment]
I don't think I really want to address these bower issues in this repo at all, but especially not from within the getting started guide with a bold-face "**Warning**". In general, I think that having a "oh by the way here are some things we're going to tell you you'll probably have to worry about but we're not going to explain fully here" during someone's first intro to a tool is generally going to be pretty bad UX.

**Comment by JordanMartinez** [comment]
It's your call, not mine.

Shall I just include the first commit and remove everything else in a force-push?

**Comment by hdgarrood** [comment]
Yes please, that would be great.

**Comment by hdgarrood** [comment]
Oh also, in case you're planning to put something like this in your learning repo, it might be worth pointing out that bower installs to `bower_components` by default, not `bower_modules`.

**Comment by JordanMartinez** [comment]
> Yes please, that would be great.

Done!

> Oh also, in case you're planning to put something like this in your learning repo, it might be worth pointing out that bower installs to bower_components by default, not bower_modules.

:rofl: whoops!

**Pull request merged**
