### PR TITLE
Add example and explaination of InfiniteType error

### PR DESCRIPTION
**Pull request by dgendill**
I'm not entirely sure my explanation of the error is correct, but the example and suggested solution might be helpful for anyone else who runs into this error.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks for putting this together, but I think we should try to find a minimal example. Here's a suggestion:

```purescript
applySelf x = x x
```

This fails because `x` must have a function type, but the domain of that function must be the same type, so we end up with an infinite type `(((... -> r) -> r) -> r) -> r`

**Comment by dgendill** [comment]
Ah, ok, that makes more sense now.  Yeah, there's a lot of extra code in my example - I'm still working through why it throws that error and why changing the types fixes it, but your example helps me see what the underlying problem is.  I went ahead and just put your example in the documentation, but I'm not sure what level of detail and explanation we're looking for, so if that's not what we're after feel free to close this PR.

**Comment by hdgarrood** [comment]
This is a good start, I think; certainly better than what we have now. Could you please use backticks `` ` `` around the code parts so it renders like in @paf31's comment, and also put a full stop at the end?

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
